/* Generated by :claw at 2020-12-24T20:29:52.389966Z */

#if defined(__cplusplus)
#include <new>
#endif

#define STB_IMAGE_IMPLEMENTATION 1

#include "stb_image.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif


__CLAW_API stbi__pngchunk* __claw_stbi__get_chunk_header(stbi__pngchunk* __claw_result, stbi__context* s) {

}

#if defined(__cplusplus)
}
#endif
