/* Generated by :claw at 2021-01-30T15:30:13.972748Z */

#if defined(__cplusplus)
#include <new>
#endif

#define STB_IMAGE_WRITE_IMPLEMENTATION 1

#include "stb_image_write.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif



#if defined(__cplusplus)
}
#endif
