;; Generated by :claw at 2021-08-09T20:53:03.372615+03:00
(asdf:defsystem #:aw-stb-image-write-bindings
  :description "Bindings generated by aw-stb-image-write"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :claw-utils)
  :components
  ((:file "bindings/image-write/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))
   (:file "bindings/image-write/aarch64-linux-android" :if-feature
    (:and :aarch64 :android))))