;; Generated by :claw at 2021-06-09T22:19:22.187989+03:00
(asdf:defsystem #:claw-stb-image-bindings
  :description "Bindings generated by claw-stb/image/wrapper"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :claw-utils)
  :components
  ((:file "bindings/image/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))
   (:file "bindings/image/aarch64-linux-android" :if-feature
    (:and :aarch64 :android))))